node {
    def commit_id
    def PUBLISH_PROFILE = 'Release'
    def msbuild = "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\msbuild.exe\""
    def nuget = "\"C:\\Program Files (x86)\\Nuget\\nuget.exe\""
    def slnName = "NetMvcApp.sln"
    def csProjName = "NetMvcApp.csproj"

    stage("Preparation") {
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id"
        commit_id = readFile('.git/commit-id').trim()
    }

    stage("Build") {
        bat "${nuget} restore \"${slnName}\""
        bat "${msbuild} ${slnName} /p:Configuration=${PUBLISH_PROFILE} /t:rebuild"
        bat "${msbuild} ${csProjName} /p:DeployOnBuild=true;PublishProfile=${PUBLISH_PROFILE}"
    }
}

